framework:
    mailer:
        dsn: 'smtp://smtp.gmail.com?port=587&encryption=tls&auth_mode=login&username=recycle.tunisia&password=ztntffukvpwraygm'
        envelope:
            sender: 'recycle.tunisia@gmail.com'