package com.mycompany.myapp;


import com.codename1.components.OnOffSwitch;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.maps.MapComponent;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.spinner.DateSpinner;
import com.codename1.ui.spinner.Picker;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    String resultat;
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
        UIBuilder uIBuilder =new UIBuilder();
        UIBuilder.registerCustomComponent("Picker", Picker.class);
        UIBuilder.registerCustomComponent("OnOffSwitch", OnOffSwitch.class);
      
        Container c =uIBuilder.createContainer(theme, "Inscription");
        Container c1 =uIBuilder.createContainer(theme, "Resultat");
        Form f2=(Form) uIBuilder.findByName("Resultat", c1);
        Form f=(Form) uIBuilder.findByName("Inscription", c);
        TextField nom=(TextField) uIBuilder.findByName("nom", c);
        TextField prenom=(TextField) uIBuilder.findByName("prenom", c);
        TextField password=(TextField) uIBuilder.findByName("password", c);
        Picker date=(Picker) uIBuilder.findByName("date", c);
        OnOffSwitch genre=(OnOffSwitch) uIBuilder.findByName("genre", c);
        CheckBox foot=(CheckBox) uIBuilder.findByName("foot", c);
        CheckBox lecture=(CheckBox) uIBuilder.findByName("lecture", c);
        CheckBox tennis=(CheckBox) uIBuilder.findByName("tennis", c);
        CheckBox natation=(CheckBox) uIBuilder.findByName("natation", c);
        Button inscription=(Button) uIBuilder.findByName("inscription", c);
     
        
        Label lnom=(Label) uIBuilder.findByName("nom", c1);
        Label lprenom=(Label) uIBuilder.findByName("prenom", c1);
        Label lpass=(Label) uIBuilder.findByName("pass", c1);
        Label ldate=(Label) uIBuilder.findByName("dateDeNaissance", c1);
        Label lgenre=(Label) uIBuilder.findByName("genre", c1);
        Label lhobbies=(Label) uIBuilder.findByName("hobbies", c1);
        String footc,lecturec,tennisc,natationc;
        inscription.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
    lnom.setText("Nom :"+nom.getText());
        lprenom.setText("Prenom :"+prenom.getText());
        lpass.setText("Password :"+password.getText());
        ldate.setText("Date de naissance :"+date.getDate().toString());
        
        if(genre.isValue())
            lgenre.setText("Gender :"+ genre.getOn());
        else 
            lgenre.setText(genre.getOff());
        if(foot.isSelected()) resultat=" " +foot.getText();
           
        if(lecture.isSelected()) resultat+="\n "+lecture.getText();
        if(tennis.isSelected()) resultat+="\n "+tennis.getText();
        if(natation.isSelected()) resultat+="\n "+natation.getText();
        
        lhobbies.setText("hobbies :"+resultat);
        f2.show();            }
        });
        
       f.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
