<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQL0uEol\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQL0uEol/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQL0uEol.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQL0uEol\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQL0uEol\App_KernelDevDebugContainer([
    'container.build_hash' => 'QL0uEol',
    'container.build_id' => 'f484e7e3',
    'container.build_time' => 1678290783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQL0uEol');
